CXXFLAGS = -O2 -Wall
CXX_LDFLAGS =
LIBRARIES =
CC = g++ -O2
CXX = g++ 

all: freader sbtost vox2reg sbtomatlabsparse

freader: freader.o

sbtost: sbtost.o

vox2reg : vox2reg.o

sbtomatlabsparse : sbtomatlabsparse.o

clean:
	rm freader sbtost vox2reg sbtomatlabsparse *.o
