#!/bin/bash

echo "Getting test data..."

loc="$PWD"
cd /tmp/
aws s3 cp --no-sign-request s3://mrneurodata/data/resources/ndmg_demo.zip /tmp/
unzip /tmp/ndmg_demo.zip

ndmg_func_pipeline /tmp/ndmg_demo/sub-0025864/ses-1/func/sub-0025864_ses-1_bold.nii.gz \
                   /tmp/ndmg_demo/sub-0025864/ses-1/anat/sub-0025864_ses-1_T1w.nii.gz  \
	 			   /tmp/ndmg_demo/MNI152NLin6_res-4x4x4_T1w.nii.gz \
	 			   /tmp/ndmg_demo/MNI152NLin6_res-4x4x4_T1w_brain.nii.gz \
	 			   /tmp/ndmg_demo/MNI152NLin6_res-4x4x4_T1w_brainmask.nii.gz \
	 			   /tmp/ndmg_demo/HarvardOxford_variant-thr25_res-4x4x4_lvmask.nii.gz \
	 			   /tmp/ndmg_demo/outputs \
				   interleaved \
				   /tmp/ndmg_demo/desikan-res-4x4x4.nii.gz

cd "$loc"
