#!/bin/bash

echo "Getting test data..."

loc="$PWD"
cd /tmp/
aws s3 cp --no-sign-request s3://mrneurodata/data/resources/ndmg_demo.zip ./
unzip /tmp/ndmg_demo.zip

ndmg_dwi_pipeline /tmp/ndmg_demo/sub-0025864/ses-1/dwi/sub-0025864_ses-1_dwi.nii.gz \
                  /tmp/ndmg_demo/sub-0025864/ses-1/dwi/sub-0025864_ses-1_dwi.bval  \
                  /tmp/ndmg_demo/sub-0025864/ses-1/dwi/sub-0025864_ses-1_dwi.bvec  \
                  /tmp/ndmg_demo/sub-0025864/ses-1/anat/sub-0025864_ses-1_T1w.nii.gz  \
    			  /tmp/ndmg_demo/MNI152NLin6_res-4x4x4_T1w.nii.gz \
	 			  /tmp/ndmg_demo/MNI152NLin6_res-4x4x4_T1w_brainmask.nii.gz \
	 			  /tmp/ndmg_demo/outputs \
				  /tmp/ndmg_demo/desikan-res-4x4x4.nii.gz

cd "$loc"
