#!/bin/bash

echo "Getting test data..."

loc="$PWD"
cd /tmp/
[ -f /tmp/ndmg_demo_dwi.zip ] || wget --quiet https://mrneurodata.s3.amazonaws.com/data/resources/ndmg_demo_dwi.zip
unzip -o /tmp/ndmg_demo_dwi.zip

ndmg_pipeline /tmp/ndmg_demo_dwi/KKI2009_113_1_DTI_s4.nii \
							/tmp/ndmg_demo_dwi/KKI2009_113_1_DTI_s4.bval \
							/tmp/ndmg_demo_dwi/KKI2009_113_1_DTI_s4.bvec \
							/tmp/ndmg_demo_dwi/KKI2009_113_1_MPRAGE_s4.nii \
							/tmp/ndmg_demo_dwi/MNI152_T1_1mm_s4.nii.gz \
							/tmp/ndmg_demo_dwi/MNI152_T1_1mm_brain_mask_s4.nii.gz \
							/tmp/ndmg_demo_dwi/outputs \
							/tmp/ndmg_demo_dwi/desikan.nii.gz

cd "$loc"
