#!/bin/bash

echo "Getting test data..."

loc="$PWD"
cd /tmp/
[ -f /tmp/ndmg_demo_func.zip ] || wget --quiet http://openconnecto.me/mrdata/share/demo_data/ndmg_demo_func.zip
unzip -o /tmp/ndmg_demo_func.zip

ndmg_func_pipeline /tmp/ndmg_demo_func/sub-0025864_session-1_bold_small.nii.gz \
	 								 /tmp/ndmg_demo_func/sub-0025864_session-1_T1w_small.nii.gz  \
	 								 /tmp/ndmg_demo_func/MNI152_T1-4mm.nii.gz \
	 								 /tmp/ndmg_demo_func/MNI152_T1-4mm_brain.nii.gz \
	 								 /tmp/ndmg_demo_func/MNI152_T1-4mm_brain_mask.nii.gz \
	 								 /tmp/ndmg_demo_func/HarvOx_lv_thr25-4mm.nii.gz \
	 								 /tmp/ndmg_demo_func/outputs \
									 interleaved \
									 /tmp/ndmg_demo_func/desikan-4mm.nii.gz

cd "$loc"
